### ISSUE TITLE
Som e vídeo

### ISSUE THREAD

**Issue by larini** [luchina-gabriel/BASE-EFI-AMD-RYZEN-THREADRIPPER#1]
Após a instalação, tive problemas com o som e com o vídeo.
O som não está funcionando, nem instalou device.
O vídeo esta´bem lento.

Meu sistema é um ryzen 7, placa msi x570a pro, e nvidia rtx2060super

O que será que faltou?

**Comment by luchina-gabriel** [comment]
Sobre o vídeo, a GPU é incompatível.
https://dortania.github.io/GPU-Buyers-Guide/

Sobre o som, tem vídeo no canal:
https://youtu.be/vddy-AouJNA
